name: Build, lint, test

on: [ push, pull_request ]

jobs:
  build-lint:
    name: Build & lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci
      - name: Compile & lint
        run: npm run lint-all

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Test
        run: npm test
